name: echo

on:
  workflow_dispatch:
    inputs:
      text:
        description: Text
        required: true
        default: 'hello there'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print
        run: echo ${{ github.event.inputs.e2eScript }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: moisesnandres/test-github-actions
          event-type: dispatch-echo-2