name: echo-2

on:
  workflow_dispatch:
    inputs:
      text:
        description: Text
        required: true
        default: 'hello there again'
  repository_dispatch:
    types: [dispatch-echo-2]

jobs:
  echo-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print
        run: echo ${{ github.event.inputs.text }}