name: echo-schedule

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  echo-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print
        run: echo hello there again from schedule