name: echo-schedule

on:
  schedule:
    - cron: '0 0 1 * *' # First day of every month

jobs:
  echo-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print
        run: echo hello there again from schedule